#-------------------------------
# General Site Settings
title: Ashlyn Im
logo: ashlyn_im_logo.png # You can add own logo.
description: Ashlyn Im Personal Website


#-------------------------------
# Author Settings
author:
  name: Ashlyn Im
  image: ashlynim_homepage.jpg
  say-hello: Hello, I’m <strong>Ashlyn</strong>
  bio: A programmer and traveller. <br/><br/> Switches my career path from business to tech and writes about <strong>data science</strong> and <strong>software engineering</strong>. I share experiences and hope to inspire futurepreneur in the tech industry.


#-------------------------------
# Contact links
# twitter: https://twitter.com/ 
facebook: https://www.facebook.com/immanyi 
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/imiminx 
linkedin: https://www.linedin.com/in/ashlynim 
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: False # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: imiminx # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
